### ISSUE TITLE
Crashes immediately on pressing scedule button

### ISSUE THREAD

**Issue by mat-de-mystify** [SecUSo/privacy-friendly-wifi-manager#18]
Every time I press scedule immediately WiFi manager crashes. It happens every time.

I really like this app and used to use smarter wifi thats no longer open source, I really hope there can be some development of this app. Thanks

**Comment by selurvedu** [comment]
Same here.

**Comment by selurvedu** [comment]
Seems to be a duplicate of #14.

**Comment by Powew230v** [comment]
The same happens to me in two android devices with lineage microG.
Unexpected closing of the app.

Greetings.

**Comment by petermayer** [comment]
I will close this issue since it is a duplicate of #14
